apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-service
    tenant: opsera
spec:
  selector:
    app: discovery-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
