apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-collector
  labels:
    app: event-collector
    tenant: opsera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-collector
  template:
    metadata:
      labels:
        app: event-collector
        tenant: opsera
    spec:
      serviceAccountName: ubr-nms
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: event-collector
          image: PLACEHOLDER_EVENT_COLLECTOR_ECR_URI
          ports:
            - containerPort: 9090
          env:
            - name: ENV
              value: "dev"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        fsGroup: 100
