apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-collector
  labels:
    app: event-collector
    tenant: opsera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-collector
  template:
    metadata:
      labels:
        app: event-collector
        tenant: opsera
    spec:
      serviceAccountName: ubr-nms
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: event-collector
          image: PLACEHOLDER_EVENT_COLLECTOR_ECR_URI
          ports:
            - containerPort: 9090
          env:
            - name: ENV
              value: "dev"
            - name: METRICS_PORT
              value: "9090"
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 20
            periodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        fsGroup: 100
