apiVersion: v1
kind: Service
metadata:
  name: event-collector
  labels:
    app: event-collector
    tenant: opsera
spec:
  selector:
    app: event-collector
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  type: ClusterIP
