#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# UBR Open NMS — Local Development Setup & Start
# Usage:  bash dev-setup.sh [--infra-only] [--no-build]
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT/dev/.env.dev"
# cd into ROOT so docker compose doesn't need to deal with the spaced path
cd "$ROOT"
COMPOSE="docker compose -f docker-compose.dev.yml"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[setup]${NC} $*"; }
warn()    { echo -e "${YELLOW}[warn]${NC}  $*"; }
error()   { echo -e "${RED}[error]${NC} $*" >&2; }

INFRA_ONLY=false
NO_BUILD=false
for arg in "$@"; do
  [[ "$arg" == "--infra-only" ]] && INFRA_ONLY=true
  [[ "$arg" == "--no-build"  ]] && NO_BUILD=true
done

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
info "Checking prerequisites..."
for cmd in docker openssl node npm; do
  if ! command -v "$cmd" &>/dev/null; then
    error "Required command not found: $cmd"
    exit 1
  fi
done
DOCKER_COMPOSE_VERSION=$(docker compose version --short 2>/dev/null || echo "0")
info "Docker Compose: $DOCKER_COMPOSE_VERSION  Node: $(node -v)  npm: $(npm -v)"

# ── 2. JWT keys ───────────────────────────────────────────────────────────────
mkdir -p "$ROOT/dev"
if [[ ! -f "$ROOT/dev/jwt_private.pem" ]]; then
  info "Generating RSA-2048 JWT key pair..."
  openssl genrsa -out "$ROOT/dev/jwt_private.pem" 2048 2>/dev/null
  openssl rsa -in "$ROOT/dev/jwt_private.pem" -pubout -out "$ROOT/dev/jwt_public.pem" 2>/dev/null
  info "Keys written to dev/jwt_private.pem + dev/jwt_public.pem"
else
  info "Using existing JWT keys in dev/"
fi

JWT_PRIV_B64=$(base64 -i "$ROOT/dev/jwt_private.pem" | tr -d '\n')
JWT_PUB_B64=$(base64 -i "$ROOT/dev/jwt_public.pem"  | tr -d '\n')

# ── 3. Write .env.dev ─────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by dev-setup.sh — do not commit
JWT_PRIVATE_KEY=${JWT_PRIV_B64}
JWT_PUBLIC_KEY=${JWT_PUB_B64}
ENVEOF
info "Wrote $ENV_FILE"

# ── 4. Install Node root deps (for monorepo tooling) ─────────────────────────
if [[ ! -d "$ROOT/node_modules" ]]; then
  info "Installing root npm dependencies..."
  npm install --silent --prefix "$ROOT" 2>/dev/null || true
fi

# ── 5. Pull infrastructure images ─────────────────────────────────────────────
info "Pulling infrastructure images (mongo, redis, kafka)..."
$COMPOSE --env-file "$ENV_FILE" pull mongo redis zookeeper kafka --quiet 2>/dev/null || \
  warn "Some image pulls failed — continuing with locally cached images"

# ── 6. Start ──────────────────────────────────────────────────────────────────
if [[ "$INFRA_ONLY" == true ]]; then
  info "Starting infrastructure only (mongo, redis, kafka)..."
  $COMPOSE --env-file "$ENV_FILE" up -d mongo redis zookeeper kafka kafka-init
else
  BUILD_FLAG=""
  [[ "$NO_BUILD" == false ]] && BUILD_FLAG="--build"
  info "Building and starting all services... (this may take 5-10 minutes on first run)"
  $COMPOSE --env-file "$ENV_FILE" up -d $BUILD_FLAG
fi

# ── 7. Wait for gateway ────────────────────────────────────────────────────────
if [[ "$INFRA_ONLY" == false ]]; then
  info "Waiting for API gateway to be healthy..."
  for i in $(seq 1 60); do
    if curl -sf http://localhost:3100/healthz >/dev/null 2>&1; then
      echo ""
      break
    fi
    printf "."
    sleep 5
  done

  echo ""
  echo ""
  echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║   UBR Open NMS is running locally!         ║${NC}"
  echo -e "${GREEN}╠════════════════════════════════════════════╣${NC}"
  echo -e "${GREEN}║${NC}  Frontend      http://localhost:5173        ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  API Gateway   http://localhost:3100        ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  Grafana       http://localhost:3030        ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}    (admin / admin)                          ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  Prometheus    http://localhost:9090        ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  Kafka         localhost:9093               ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  MongoDB       localhost:27017              ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  Redis         localhost:6380 (→ 6379)      ${GREEN}║${NC}"
  echo -e "${GREEN}╠════════════════════════════════════════════╣${NC}"
  echo -e "${GREEN}║${NC}  Logs:  docker compose -f docker-compose.dev.yml logs -f  ${GREEN}║${NC}"
  echo -e "${GREEN}║${NC}  Stop:  docker compose -f docker-compose.dev.yml down     ${GREEN}║${NC}"
  echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
else
  echo ""
  echo -e "${GREEN}Infrastructure ready:${NC}"
  echo "  MongoDB  → localhost:27017"
  echo "  Redis    → localhost:6379"
  echo "  Kafka    → localhost:9093"
  echo ""
  echo "Run individual services natively for faster development:"
  echo "  Auth:     cd services/auth-service && npm run dev"
  echo "  Alarm:    cd services/alarm-service && mvn spring-boot:run"
fi
