apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsera-ubr-nms-alarm-service-dev
  namespace: argocd
  labels:
    tenant: opsera
    app: ubr-nms
    service: alarm-service
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/gayathri-opsera/UBR-Open-NMS.git
    targetRevision: main
    path: .opsera-ubr-nms/k8s/alarm-service/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-ubr-nms-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
