apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    tenant: opsera
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tenant: opsera
    spec:
      serviceAccountName: ubr-nms
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: frontend
          image: PLACEHOLDER_FRONTEND_ECR_URI
          ports:
            - containerPort: 80
          env:
            - name: ENV
              value: "dev"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
      securityContext:
        runAsNonRoot: false
