apiVersion: v1
kind: Service
metadata:
  name: netcool-forwarder
  labels:
    app: netcool-forwarder
    tenant: opsera
spec:
  selector:
    app: netcool-forwarder
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
