apiVersion: v1
kind: Service
metadata:
  name: topology-service
  labels:
    app: topology-service
    tenant: opsera
spec:
  selector:
    app: topology-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
  type: ClusterIP
