apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-ubr-nms-dev

resources:
- ../../base
- namespace.yaml

images:
- name: PLACEHOLDER_FRONTEND_ECR_URI
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ubr-nms-frontend
  newTag: dev-8d50e8a3-20260713013458

labels:
- pairs:
    environment: dev
    tenant: opsera
