apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-ubr-nms-dev

resources:
- ../../base
- namespace.yaml

images:
- name: PLACEHOLDER_CONFIG_SERVICE_ECR_URI
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ubr-nms-config-service
  newTag: dev-de0265ae-20260710053425

labels:
- pairs:
    environment: dev
    tenant: opsera
