package com.ubrnms.config.service;

import com.ubrnms.config.model.ConfigTargetPreviewResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

/**
 * In-memory preview cache with TTL expiry for WO-045 confirmation gate.
 *
 * <p>Previews generated by {@link TargetResolverService} are stored here so that
 * the confirmation endpoint can look them up by previewId, check their freshness,
 * and validate target counts before creating an accepted job.
 *
 * <p>TTL defaults to 10 minutes to ensure the operator is confirming a reasonably
 * current view of the target set. Previews older than this window are considered
 * stale and confirmation is blocked with a structured conflict response.
 *
 * <p>A scheduled cleanup task removes expired entries to prevent unbounded memory
 * growth in long-running deployments.
 */
@Slf4j
@Service
public class PreviewStoreService {

    @Value("${config.preview.ttl-minutes:10}")
    private int ttlMinutes;

    record CachedPreview(ConfigTargetPreviewResponse preview, Instant storedAt) {}

    private final ConcurrentHashMap<String, CachedPreview> store = new ConcurrentHashMap<>();

    /**
     * Store a newly generated preview.
     * Called by {@link TargetResolverService} after every successful resolution.
     */
    public void store(ConfigTargetPreviewResponse preview) {
        if (preview == null || preview.getPreviewId() == null) return;
        store.put(preview.getPreviewId(), new CachedPreview(preview, Instant.now()));
        log.debug("Stored preview id={} targets={}", preview.getPreviewId(), preview.getTotalCount());
    }

    /**
     * Look up a preview by its opaque ID.
     *
     * @param previewId the ID returned to the client in the preview response
     * @return the cached preview, or empty if absent or expired
     */
    public Optional<ConfigTargetPreviewResponse> find(String previewId) {
        CachedPreview cached = store.get(previewId);
        if (cached == null) return Optional.empty();
        if (isExpired(cached)) {
            store.remove(previewId);
            log.debug("Preview id={} has expired", previewId);
            return Optional.empty();
        }
        return Optional.of(cached.preview());
    }

    /**
     * Returns true if the preview has been in the store longer than {@code ttlMinutes}.
     * Also returns true if {@code generatedAt} on the preview itself is stale,
     * guarding against clock skew between TTL check and preview generation time.
     */
    public boolean isExpired(String previewId) {
        CachedPreview cached = store.get(previewId);
        if (cached == null) return true;
        return isExpired(cached);
    }

    private boolean isExpired(CachedPreview cached) {
        return cached.storedAt().isBefore(Instant.now().minus(ttlMinutes, ChronoUnit.MINUTES));
    }

    /** Invalidate a preview after successful job creation to prevent replay. */
    public void invalidate(String previewId) {
        store.remove(previewId);
        log.debug("Invalidated preview id={}", previewId);
    }

    /** Scheduled TTL cleanup — removes all expired entries every 5 minutes. */
    @Scheduled(fixedDelayString = "${config.preview.cleanup-interval-ms:300000}")
    public void expireStaleEntries() {
        Instant threshold = Instant.now().minus(ttlMinutes, ChronoUnit.MINUTES);
        int removed = 0;
        for (var entry : store.entrySet()) {
            if (entry.getValue().storedAt().isBefore(threshold)) {
                store.remove(entry.getKey());
                removed++;
            }
        }
        if (removed > 0) {
            log.info("Preview store cleanup: removed {} expired entries", removed);
        }
    }

    /** Returns the number of active (non-expired) previews in the cache. */
    public int size() {
        return store.size();
    }
}
