apiVersion: v2
name: event-collector
description: UBR NMS Event Collector
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: ubrnms-common
    version: "1.0.0"
    repository: "file://../ubrnms-common"
