apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-ubr-nms-dev

resources:
- ../../base
- namespace.yaml

images:
- name: PLACEHOLDER_MOBINET_SYNC_ECR_URI
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ubr-nms-mobinet-sync
  newTag: dev-d1573382-20260710045625

labels:
- pairs:
    environment: dev
    tenant: opsera
