apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobinet-sync
  labels:
    app: mobinet-sync
    tenant: opsera
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mobinet-sync
  template:
    metadata:
      labels:
        app: mobinet-sync
        tenant: opsera
    spec:
      serviceAccountName: ubr-nms
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: mobinet-sync
          image: PLACEHOLDER_MOBINET_SYNC_ECR_URI
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKERS
              value: "kafka.opsera-ubr-nms-dev.svc.cluster.local:9092"
            - name: KAFKA_ENABLED
              value: "true"
            - name: ENV
              value: "dev"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        fsGroup: 100
