package com.ubrnms.config.model;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Payload for POST /api/v1/config/actions/confirm (WO-045).
 *
 * <p>Binds a config execution request to a previously generated target preview,
 * validates the target count, and records the approving actor before creating
 * an accepted async job.
 *
 * <p>Must NOT include credentials, rendered secrets, or southbound connection
 * parameters — only intent, identity, and preview correlation fields.
 */
@Data
@NoArgsConstructor
public class ConfirmExecutionRequest {

    /**
     * Preview ID returned by POST /api/v1/config/targets/preview (WO-039).
     * Server-side validation ensures this preview is still current and unexpired.
     */
    @NotBlank(message = "previewId is required")
    private String previewId;

    /**
     * Operation type being confirmed.
     * Must match the actionType in the original preview.
     * Values: CONFIG_PUSH | FIRMWARE_UPGRADE | PARAMETER_CHANGE | COMMAND_EXECUTE
     */
    @NotBlank(message = "actionType is required")
    private String actionType;

    /**
     * Template or policy reference to apply.
     * May be absent for COMMAND_EXECUTE or PARAMETER_CHANGE actions.
     */
    private String templateId;

    /**
     * Target device count the operator is confirming.
     * Must exactly match the current preview's total target count.
     * Prevents accidental broad execution if the target set changed since preview.
     */
    @NotNull(message = "expectedTargetCount is required")
    @Positive(message = "expectedTargetCount must be greater than 0")
    private Integer expectedTargetCount;

    /**
     * Whether the operator explicitly acknowledged warnings present in the preview
     * (e.g. "X devices are offline and will be queued").
     * Execution is allowed regardless of this flag, but the value is recorded
     * for audit purposes.
     */
    private boolean acceptWarnings;

    /**
     * Optional external approval reference (ITIL change record, JIRA ticket, etc.).
     * Stored on the job for compliance audit trails when present.
     */
    private String approvalReference;

    /**
     * Client-supplied idempotency key.
     * If a job already exists with this key and the same previewId, the existing
     * accepted job is returned instead of creating a duplicate.
     * Should be a UUID generated by the frontend before the confirmation dialog is shown.
     */
    private String idempotencyKey;
}
