apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ubrnms-common.fullname" . }}
  namespace: {{ .Values.namespace | default "ubr-platform" }}
  labels:
    {{- include "ubrnms-common.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ubrnms-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ubrnms-common.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ubrnms-common.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          livenessProbe:
            {{- include "ubrnms-common.livenessProbe" . | nindent 12 }}
          readinessProbe:
            {{- include "ubrnms-common.readinessProbe" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
