apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-monitor
  labels:
    app: health-monitor
    tenant: opsera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-monitor
  template:
    metadata:
      labels:
        app: health-monitor
        tenant: opsera
    spec:
      serviceAccountName: ubr-nms
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: health-monitor
          image: PLACEHOLDER_HEALTH_MONITOR_ECR_URI
          ports:
            - containerPort: 8092
          env:
            - name: ENV
              value: "dev"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8092
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8092
            initialDelaySeconds: 60
            periodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        fsGroup: 100
