apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-ubr-nms-dev

resources:
- ../../base
- namespace.yaml

images:
- name: PLACEHOLDER_API_GATEWAY_ECR_URI
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/ubr-nms-api-gateway
  newTag: dev-979cd8f7-20260828214738

labels:
- pairs:
    environment: dev
    tenant: opsera
