apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
    tenant: opsera
spec:
  selector:
    app: config-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP
