replicaCount: 2

image:
  repository: ubrnms/api-gateway
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3010

containerPort: 3010

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

probes:
  liveness:
    initialDelaySeconds: 20
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 5

namespace: ubr-ingress

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts: []
  tls: []

env:
  - name: SERVICE_NAME
    value: "api-gateway"

networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ubr-platform
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ubr-ingress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ubr-data
