apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    tenant: opsera
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
  type: ClusterIP
